# Generated by Django 4.2.1 on 2023-05-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
