# Generated by Django 4.2.1 on 2023-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
